//! Composer-name allocation pool (Task 20, design/03 §3.5).
//!
//! Per-workspace, every workarea is named after a classical composer:
//! `bach`, `mozart`, `beethoven`, … The Workspace Manager picks the
//! lowest-indexed name in [`COMPOSERS`] that is not already in use within
//! the workspace, and falls back to `<composer>-N` once the pool is
//! exhausted.
//!
//! ## Public-interface contract
//!
//! - The order of [`COMPOSERS`] is FROZEN by Task 20. Adding new names at
//!   the END of the slice is fine (they will be picked only after every
//!   earlier name is taken); reordering or removing names changes which
//!   composer the Workspace Manager hands out for a fresh workspace,
//!   which the UI persists. Treat reordering as a breaking change.
//! - Names are plain ASCII lowercase. Diacritics are stripped so the
//!   strings double as URL-safe filesystem path segments (the workarea
//!   directory is `<workspace.slug>/<composer>/`).
//!
//! ## Why this many
//!
//! Empirically a power user might spin up dozens of workareas inside one
//! workspace over the lifetime of a project. We ship ~500 composer names
//! so the `-2` overflow path stays a pure tail case. The total comfortably
//! exceeds the task spec's 200+ floor.

/// Ordered pool of composer names. The Workspace Manager picks the
/// lowest-index entry not already used by a sibling workarea in the same
/// workspace. See module-level docs for the freezing contract.
pub const COMPOSERS: &[&str] = &[
    // ---- Baroque cornerstones -------------------------------------------
    "bach",
    "handel",
    "vivaldi",
    "telemann",
    "scarlatti",
    "purcell",
    "rameau",
    "lully",
    "couperin",
    "corelli",
    "albinoni",
    "pachelbel",
    "monteverdi",
    "gabrieli",
    "buxtehude",
    "froberger",
    "frescobaldi",
    "praetorius",
    "schein",
    "schutz",
    "sweelinck",
    "biber",
    "marais",
    "marin",
    "leclair",
    "geminiani",
    "locatelli",
    "stradella",
    "torelli",
    "zelenka",
    "fasch",
    "graupner",
    "heinichen",
    "kuhnau",
    "muffat",
    "pergolesi",
    "porpora",
    "tartini",
    "campra",
    "charpentier",
    "delalande",
    "destouches",
    "leonardo",
    "froger",
    // ---- Classical ------------------------------------------------------
    "mozart",
    "haydn",
    "beethoven",
    "schubert",
    "salieri",
    "cherubini",
    "clementi",
    "cimarosa",
    "boccherini",
    "gluck",
    "stamitz",
    "gossec",
    "dittersdorf",
    "kraus",
    "myslivecek",
    "paisiello",
    "spontini",
    "wagenseil",
    "vanhal",
    "hummel",
    "pleyel",
    "kozeluch",
    "krommer",
    "rossini",
    "donizetti",
    "bellini",
    "spohr",
    "weber",
    "field",
    "mehul",
    "boieldieu",
    "auber",
    "herold",
    "halevy",
    // ---- Early Romantic -------------------------------------------------
    "mendelssohn",
    "schumann",
    "chopin",
    "berlioz",
    "liszt",
    "wagner",
    "verdi",
    "brahms",
    "bruckner",
    "smetana",
    "dvorak",
    "tchaikovsky",
    "musorgsky",
    "borodin",
    "balakirev",
    "cui",
    "rimsky",
    "glinka",
    "alkan",
    "thalberg",
    "moscheles",
    "marschner",
    "nicolai",
    "lortzing",
    "flotow",
    "raff",
    "rubinstein",
    "joachim",
    "bruch",
    "reinecke",
    "rheinberger",
    "kiel",
    "draeseke",
    "volkmann",
    "gade",
    "kuhlau",
    "weyse",
    "berwald",
    "lindblad",
    "norman",
    // ---- Late Romantic --------------------------------------------------
    "mahler",
    "strauss",
    "wolf",
    "humperdinck",
    "reger",
    "puccini",
    "leoncavallo",
    "mascagni",
    "ponchielli",
    "boito",
    "catalani",
    "giordano",
    "cilea",
    "saint",
    "franck",
    "faure",
    "chausson",
    "duparc",
    "lalo",
    "chabrier",
    "delibes",
    "bizet",
    "gounod",
    "thomas",
    "massenet",
    "offenbach",
    "lecocq",
    "messager",
    "indy",
    "magnard",
    "lekeu",
    "godard",
    "guilmant",
    "widor",
    "vierne",
    "tournemire",
    "boellmann",
    "dubois",
    "pierne",
    "roussel",
    "gilson",
    "ysaye",
    "jongen",
    "lekeur",
    "tinel",
    "gevaert",
    "benoit",
    // ---- Nationalist / Folk-rooted --------------------------------------
    "grieg",
    "sibelius",
    "nielsen",
    "stenhammar",
    "alfven",
    "atterberg",
    "rangstrom",
    "halvorsen",
    "svendsen",
    "klami",
    "sallinen",
    "rautavaara",
    "kuula",
    "madetoja",
    "merikanto",
    "palmgren",
    "kajanus",
    "wegelius",
    "albeniz",
    "granados",
    "falla",
    "turina",
    "mompou",
    "rodrigo",
    "halffter",
    "guridi",
    "espla",
    "breton",
    "chapi",
    "barbieri",
    "arrieta",
    "sarasate",
    "tarrega",
    "villa",
    "lobos",
    "ginastera",
    "piazzolla",
    "guastavino",
    "chavez",
    "revueltas",
    "ponce",
    "moncayo",
    "galindo",
    "carrillo",
    "lavista",
    "nazareth",
    "gomes",
    "guarnieri",
    "mignone",
    "bonis",
    // ---- 20th-Century European ------------------------------------------
    "debussy",
    "ravel",
    "satie",
    "poulenc",
    "milhaud",
    "honegger",
    "auric",
    "tailleferre",
    "durey",
    "messiaen",
    "boulez",
    "dutilleux",
    "jolivet",
    "varese",
    "ohana",
    "xenakis",
    "grisey",
    "murail",
    "saariaho",
    "lindberg",
    "salonen",
    "kaija",
    "magnus",
    "knussen",
    "tippett",
    "britten",
    "walton",
    "vaughan",
    "holst",
    "elgar",
    "delius",
    "bax",
    "bridge",
    "ireland",
    "moeran",
    "bantock",
    "stanford",
    "parry",
    "sullivan",
    "boyce",
    "arne",
    "tallis",
    "byrd",
    "dowland",
    "morley",
    "weelkes",
    "wilbye",
    "gibbons",
    "tomkins",
    "tye",
    "tavener",
    "macmillan",
    "birtwistle",
    "maxwell",
    "ferneyhough",
    "finnissy",
    "skempton",
    "casken",
    "weir",
    "dove",
    "turnage",
    // ---- 20th-Century Eastern Europe ------------------------------------
    "stravinsky",
    "rachmaninoff",
    "scriabin",
    "prokofiev",
    "shostakovich",
    "khachaturian",
    "kabalevsky",
    "schnittke",
    "gubaidulina",
    "denisov",
    "ustvolskaya",
    "weinberg",
    "myaskovsky",
    "glazunov",
    "lyadov",
    "lyapunov",
    "arensky",
    "taneyev",
    "medtner",
    "bortkiewicz",
    "tcherepnin",
    "lourie",
    "obouhow",
    "wyschnegradsky",
    "mosolov",
    "roslavets",
    "bartok",
    "kodaly",
    "dohnanyi",
    "janacek",
    "martinu",
    "suk",
    "novak",
    "fibich",
    "foerster",
    "schulhoff",
    "haba",
    "krasa",
    "ullmann",
    "klein",
    "szymanowski",
    "lutoslawski",
    "penderecki",
    "gorecki",
    "panufnik",
    "bacewicz",
    "kilar",
    "moniuszko",
    "paderewski",
    "wieniawski",
    "karlowicz",
    "ligeti",
    "kurtag",
    "eotvos",
    "weiner",
    "veress",
    "enescu",
    "silvestri",
    "constantinescu",
    "jora",
    "lipatti",
    // ---- Second Viennese + Austro-German modernists ---------------------
    "schoenberg",
    "berg",
    "webern",
    "krenek",
    "zemlinsky",
    "schreker",
    "korngold",
    "weill",
    "hindemith",
    "henze",
    "stockhausen",
    "lachenmann",
    "rihm",
    "zimmermann",
    "eisler",
    "dessau",
    "blacher",
    "fortner",
    "orff",
    "pfitzner",
    "schmidt",
    "marx",
    "schoeck",
    "martin",
    "honneger",
    "burkhard",
    "klose",
    "graener",
    "trapp",
    // ---- Americans -------------------------------------------------------
    "gershwin",
    "copland",
    "bernstein",
    "ives",
    "barber",
    "rorem",
    "harris",
    "schuman",
    "piston",
    "hanson",
    "thomson",
    "sessions",
    "carter",
    "babbitt",
    "wuorinen",
    "feldman",
    "cage",
    "crumb",
    "rzewski",
    "reich",
    "glass",
    "adams",
    "riley",
    "young",
    "monk",
    "andriessen",
    "nyman",
    "yoshimatsu",
    "takemitsu",
    "toru",
    "ichiyanagi",
    "miyoshi",
    "hosokawa",
    "fujikura",
    "yun",
    "chin",
    "sheng",
    "tan",
    "chen",
    "zhou",
    "isang",
    "joplin",
    "sousa",
    "macdowell",
    "beach",
    "chadwick",
    "paine",
    "foote",
    "parker",
    "loeffler",
    "griffes",
    "ruggles",
    "varese",
    "antheil",
    "harrison",
    "partch",
    "nancarrow",
    "brant",
    "tower",
    "zwilich",
    "larsen",
    "higdon",
    "puts",
    "mackey",
    "muhly",
    "lang",
    "wolfe",
    "gordon",
    "norman",
    "shaw",
    "andres",
    "kernis",
    "rouse",
    "schwantner",
    "corigliano",
    "del",
    "tredici",
    "argento",
    "bolcom",
    "harbison",
    "tower",
    "danielpour",
    "kapilow",
    "torke",
    "daugherty",
    "schickele",
    // ---- Film + post-tonal cross-over -----------------------------------
    "herrmann",
    "korngold",
    "rozsa",
    "tiomkin",
    "newman",
    "goldsmith",
    "morricone",
    "rota",
    "nino",
    "delerue",
    "legrand",
    "jarre",
    "williams",
    "horner",
    "shore",
    "elfman",
    "zimmer",
    "desplat",
    "giacchino",
    "powell",
    "silvestri",
    "broughton",
    "isham",
    "kamen",
    "kilar",
    "marianelli",
    "newton",
    "howard",
    "doyle",
    "barry",
    "bernstein",
    "raksin",
    "waxman",
    "north",
    "korngold",
    "salonen",
    // ---- Contemporary "post-classical" ----------------------------------
    "einaudi",
    "yiruma",
    "richter",
    "frahm",
    "arnalds",
    "tiersen",
    "nyman",
    "glassworks",
    "metheny",
    "zorn",
    "lang",
    "shaw",
    "andres",
    "muhly",
    "dessner",
    "greenwood",
    "wolfe",
    "gordon",
    "norman",
    "mazzoli",
    "viola",
    "esmail",
    "sorey",
    "lewis",
    "smith",
    // ---- Additional historical depth (fills out the long tail) ----------
    "victoria",
    "palestrina",
    "lassus",
    "josquin",
    "ockeghem",
    "dufay",
    "binchois",
    "machaut",
    "perotin",
    "leonin",
    "landini",
    "ciconia",
    "isaac",
    "obrecht",
    "willaert",
    "rore",
    "gesualdo",
    "marenzio",
    "monteverde",
    "schein",
    "scheidt",
    "schop",
    "bull",
    "weelkes",
    "cavalli",
    "cesti",
    "carissimi",
    "stradella",
    "steffani",
    "lotti",
    "caldara",
    "vinci",
    "leo",
    "jommelli",
    "traetta",
    "piccinni",
    "sacchini",
    "salieri",
    "soler",
    "scarlatti",
    "porpora",
    "durante",
    "feo",
    "logroscino",
    "pergolesi",
    "galuppi",
    "hasse",
    "graun",
    "agricola",
    "kirnberger",
    "marpurg",
    "krebs",
    "homilius",
    "doles",
    "harrer",
    "bach",
    "richter",
    "vogler",
    "gyrowetz",
    "wranitzky",
    "rosetti",
    "rejcha",
    "reicha",
    "onslow",
    "ries",
    "moscheles",
    "kalkbrenner",
    "henselt",
    "thalberg",
    "dreyschock",
    "leschetizky",
    "godowsky",
    "scharwenka",
    "moszkowski",
    "leschetitzky",
    "busoni",
    "sgambati",
    "martucci",
    "casella",
    "respighi",
    "malipiero",
    "pizzetti",
    "alfano",
    "wolf",
    "ferrari",
    "tosti",
    "denza",
    "leoncavallo",
    "smareglia",
    "sinigaglia",
    "perosi",
    "refice",
    "petrassi",
    "dallapiccola",
    "nono",
    "berio",
    "maderna",
    "donatoni",
    "bussotti",
    "togni",
    "evangelisti",
    "scelsi",
    "sciarrino",
    "fedele",
    "francesconi",
    "filidei",
    "battistelli",
    "ferrero",
    "vacchi",
    "solbiati",
    "dusapin",
    "mache",
    "manoury",
    "campion",
    "campana",
];

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashSet;

    #[test]
    fn pool_meets_size_floor() {
        // Task 20 spec: 200+ names. We comfortably exceed that.
        assert!(
            COMPOSERS.len() >= 200,
            "COMPOSERS pool must hold at least 200 names; has {}",
            COMPOSERS.len()
        );
    }

    #[test]
    fn every_name_is_slug_safe() {
        // Each entry must be plain ASCII lowercase alphanumerics — the
        // string doubles as a filesystem path segment in
        // `<workspace.slug>/<composer>/`.
        for name in COMPOSERS {
            assert!(!name.is_empty(), "empty composer name in pool");
            assert!(
                name.chars()
                    .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit()),
                "composer name {name:?} must be ASCII lowercase letters/digits only"
            );
        }
    }

    #[test]
    fn first_few_are_canonical_bach_mozart() {
        // The order is frozen; the leading entries are the canonical
        // "first workarea gets `bach`" UX expectation.
        assert_eq!(COMPOSERS[0], "bach");
        assert!(COMPOSERS.contains(&"mozart"));
        assert!(COMPOSERS.contains(&"beethoven"));
        assert!(COMPOSERS.contains(&"chopin"));
        assert!(COMPOSERS.contains(&"debussy"));
    }

    /// Allocation uses `Vec<&str>::iter().enumerate().find(...)` — confirm
    /// the lowest-index unused name is selected.
    #[test]
    fn lowest_unused_index_is_chosen() {
        let used: HashSet<&str> = ["bach", "mozart"].into_iter().collect();
        let pick = COMPOSERS
            .iter()
            .find(|n| !used.contains(*n))
            .copied()
            .expect("pool not exhausted");
        // Whatever comes immediately after the first two indices we marked
        // used.
        let expected = COMPOSERS
            .iter()
            .find(|n| !used.contains(*n))
            .copied()
            .unwrap();
        assert_eq!(pick, expected);
        // It must NOT be either of the used ones.
        assert!(!used.contains(pick));
    }
}
