//! gRPC handler impls (Task 13).
//!
//! Each submodule implements the trait generated by `concerto-proto`
//! for one service. Handlers are deliberately thin: they translate
//! `tonic::Request` into a call against the runtime's owned state
//! and translate the result back through [`crate::error_map`].

pub mod projects;
pub mod repositories;
pub mod runtime;
#[cfg(unix)]
pub mod schedules;
#[cfg(unix)]
pub mod sessions;
pub mod skills;
#[cfg(unix)]
pub mod streams;
#[cfg(unix)]
pub mod suggestions;
pub mod workareas;
pub mod workspaces;
