//! `pull_requests` table CRUD (Task 45).
//!
//! Caches per-(workarea, repository) PR state for the VCS Provider
//! Integration (`design/13`). The canonical state is GitHub's; this
//! table is a cache the UI reads from so the workarea PR panel does
//! not block on a `gh` round-trip on every render.
//!
//! Schema is locked by migration 0008, extended additively by 0014
//! (Task 319: `merge_order`, `external_id`, `repository_full_name`):
//!
//! ```sql
//! CREATE TABLE pull_requests (
//!     id TEXT PRIMARY KEY,
//!     workarea_id TEXT NOT NULL REFERENCES workareas(id) ON DELETE CASCADE,
//!     repository_id TEXT NOT NULL REFERENCES repositories(id),
//!     provider TEXT NOT NULL,
//!     pr_number INTEGER NOT NULL,
//!     base_ref TEXT NOT NULL,
//!     head_ref TEXT NOT NULL,
//!     state TEXT NOT NULL,
//!     title TEXT NOT NULL,
//!     body TEXT NOT NULL DEFAULT '',
//!     url TEXT NOT NULL DEFAULT '',
//!     head_sha TEXT NOT NULL DEFAULT '',
//!     merge_order INTEGER NOT NULL DEFAULT 0,           -- 0014
//!     external_id TEXT NOT NULL DEFAULT '',             -- 0014 (GraphQL node id)
//!     repository_full_name TEXT NOT NULL DEFAULT '',    -- 0014 (owner/repo)
//!     created_at INTEGER NOT NULL,
//!     updated_at INTEGER NOT NULL,
//!     UNIQUE(workarea_id, repository_id)
//! );
//! ```
//!
//! The workarea's PR set is the implicit set of rows for a `workarea_id`,
//! ordered `(merge_order, pr_number)`. `merge_order` defaults to insertion
//! order (`max(merge_order)+1` per workarea, see [`next_merge_order`]) and
//! is preserved across upserts so a re-sync never resets a user's reorder;
//! `external_id` / `repository_full_name` refresh on every upsert.
//!
//! Public types are declared in [`crate::api`] so the interface
//! generator picks them up.

use concerto_error::{Error, Result};
use sqlx::{Row, SqliteConnection, SqlitePool};

use crate::api::{NewPullRequest, PullRequest, PullRequestId};

/// Insert OR update the row keyed by `(workarea_id, repository_id)`.
///
/// `id` is generated by the caller (UUIDv7) and used only on the
/// first insert — subsequent upserts keep the existing primary key so
/// callers holding the original id stay valid. `created_at` and
/// `merge_order` are also preserved across upserts (kept out of the
/// `DO UPDATE SET` clause); `updated_at`, `external_id`, and
/// `repository_full_name` always advance to the caller-supplied value.
/// Because `merge_order` only takes effect on the first insert, callers
/// should compute the insertion-order default via [`next_merge_order`]
/// under the same writer lock as this call so the `MAX` and the insert
/// stay atomic.
pub async fn upsert(conn: &mut SqliteConnection, row: NewPullRequest) -> Result<PullRequestId> {
    sqlx::query(
        "INSERT INTO pull_requests (
            id, workarea_id, repository_id, provider, pr_number,
            base_ref, head_ref, state, title, body, url, head_sha,
            merge_order, external_id, repository_full_name,
            created_at, updated_at
         ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
         ON CONFLICT(workarea_id, repository_id) DO UPDATE SET
            provider             = excluded.provider,
            pr_number            = excluded.pr_number,
            base_ref             = excluded.base_ref,
            head_ref             = excluded.head_ref,
            state                = excluded.state,
            title                = excluded.title,
            body                 = excluded.body,
            url                  = excluded.url,
            head_sha             = excluded.head_sha,
            external_id          = excluded.external_id,
            repository_full_name = excluded.repository_full_name,
            updated_at           = excluded.updated_at",
    )
    .bind(&row.id.0)
    .bind(&row.workarea_id.0)
    .bind(&row.repository_id.0)
    .bind(&row.provider)
    .bind(row.pr_number)
    .bind(&row.base_ref)
    .bind(&row.head_ref)
    .bind(&row.state)
    .bind(&row.title)
    .bind(&row.body)
    .bind(&row.url)
    .bind(&row.head_sha)
    .bind(row.merge_order)
    .bind(&row.external_id)
    .bind(&row.repository_full_name)
    .bind(row.created_at)
    .bind(row.updated_at)
    .execute(&mut *conn)
    .await
    .map_err(|e| Error::Sqlx(Box::new(e)))?;

    // Resolve the canonical id (the existing one if this was an UPDATE,
    // the new one otherwise). One SELECT keeps the upsert call site
    // honest about which id the caller now owns.
    let resolved: String = sqlx::query_scalar(
        "SELECT id FROM pull_requests WHERE workarea_id = ? AND repository_id = ?",
    )
    .bind(&row.workarea_id.0)
    .bind(&row.repository_id.0)
    .fetch_one(conn)
    .await
    .map_err(|e| Error::Sqlx(Box::new(e)))?;
    Ok(PullRequestId(resolved))
}

/// Fetch one PR by primary key (read-only).
pub async fn get(pool: &SqlitePool, id: &PullRequestId) -> Result<Option<PullRequest>> {
    let row = sqlx::query(
        "SELECT id, workarea_id, repository_id, provider, pr_number,
                base_ref, head_ref, state, title, body, url, head_sha,
                merge_order, external_id, repository_full_name,
                created_at, updated_at
         FROM pull_requests WHERE id = ?",
    )
    .bind(&id.0)
    .fetch_optional(pool)
    .await
    .map_err(|e| Error::Sqlx(Box::new(e)))?;
    Ok(row.map(row_to_pull_request))
}

/// List every PR for `workarea_id` (read-only) — the workarea's implicit
/// PR set. Ordered `(merge_order, pr_number)`: the user-reorderable merge
/// plan position first (Task 319), with `pr_number` as the deterministic
/// tie-breaker when two rows share a `merge_order`.
pub async fn list_by_workarea(
    pool: &SqlitePool,
    workarea_id: &crate::api::WorkareaId,
) -> Result<Vec<PullRequest>> {
    let rows = sqlx::query(
        "SELECT id, workarea_id, repository_id, provider, pr_number,
                base_ref, head_ref, state, title, body, url, head_sha,
                merge_order, external_id, repository_full_name,
                created_at, updated_at
         FROM pull_requests WHERE workarea_id = ?
         ORDER BY merge_order, pr_number",
    )
    .bind(&workarea_id.0)
    .fetch_all(pool)
    .await
    .map_err(|e| Error::Sqlx(Box::new(e)))?;
    Ok(rows.into_iter().map(row_to_pull_request).collect())
}

/// The insertion-order default for a new PR in `workarea_id`:
/// `max(merge_order) + 1` over the workarea's existing rows (or `0` for
/// the first PR). Per `PHASE3_PLANNING.md D7`. Run this on the SAME writer
/// connection as the follow-on [`upsert`] so the `MAX` and the insert are
/// atomic under the serialized persistence writer lock.
pub async fn next_merge_order(
    conn: &mut SqliteConnection,
    workarea_id: &crate::api::WorkareaId,
) -> Result<i64> {
    let next: i64 = sqlx::query_scalar(
        "SELECT COALESCE(MAX(merge_order), -1) + 1
         FROM pull_requests WHERE workarea_id = ?",
    )
    .bind(&workarea_id.0)
    .fetch_one(conn)
    .await
    .map_err(|e| Error::Sqlx(Box::new(e)))?;
    Ok(next)
}

/// Set the `merge_order` of one PR row (Task 319 `SetMergeOrder`). Returns
/// `NotFound` if no row has the given id. Only mutates `merge_order` — the
/// cached PR fields keep their last-synced values.
pub async fn set_merge_order(
    conn: &mut SqliteConnection,
    id: &PullRequestId,
    order: i64,
) -> Result<()> {
    let affected = sqlx::query("UPDATE pull_requests SET merge_order = ? WHERE id = ?")
        .bind(order)
        .bind(&id.0)
        .execute(conn)
        .await
        .map_err(|e| Error::Sqlx(Box::new(e)))?
        .rows_affected();
    if affected == 0 {
        return Err(Error::NotFound(format!("pull_request {id} not found")));
    }
    Ok(())
}

/// Resolve a PR id by `(workarea_id, repository_id)` — the implicit PR-set
/// key (`UNIQUE(workarea_id, repository_id)`). Used by `SetMergeOrder` to
/// turn the wire's `(workarea, repository)` pair into the row's primary
/// key. Returns `None` when the workarea has no PR for that repository.
pub async fn id_by_workarea_repo(
    pool: &SqlitePool,
    workarea_id: &crate::api::WorkareaId,
    repository_id: &crate::api::RepositoryId,
) -> Result<Option<PullRequestId>> {
    let resolved: Option<String> = sqlx::query_scalar(
        "SELECT id FROM pull_requests WHERE workarea_id = ? AND repository_id = ?",
    )
    .bind(&workarea_id.0)
    .bind(&repository_id.0)
    .fetch_optional(pool)
    .await
    .map_err(|e| Error::Sqlx(Box::new(e)))?;
    Ok(resolved.map(PullRequestId))
}

fn row_to_pull_request(row: sqlx::sqlite::SqliteRow) -> PullRequest {
    use crate::api::{RepositoryId, WorkareaId};
    PullRequest {
        id: PullRequestId(row.get::<String, _>("id")),
        workarea_id: WorkareaId(row.get::<String, _>("workarea_id")),
        repository_id: RepositoryId(row.get::<String, _>("repository_id")),
        provider: row.get::<String, _>("provider"),
        pr_number: row.get::<i64, _>("pr_number"),
        base_ref: row.get::<String, _>("base_ref"),
        head_ref: row.get::<String, _>("head_ref"),
        state: row.get::<String, _>("state"),
        title: row.get::<String, _>("title"),
        body: row.get::<String, _>("body"),
        url: row.get::<String, _>("url"),
        head_sha: row.get::<String, _>("head_sha"),
        merge_order: row.get::<i64, _>("merge_order"),
        external_id: row.get::<String, _>("external_id"),
        repository_full_name: row.get::<String, _>("repository_full_name"),
        created_at: row.get::<i64, _>("created_at"),
        updated_at: row.get::<i64, _>("updated_at"),
    }
}
