//! `pull_requests` table CRUD (Task 45).
//!
//! Caches per-(workarea, repository) PR state for the VCS Provider
//! Integration (`design/13`). The canonical state is GitHub's; this
//! table is a cache the UI reads from so the workarea PR panel does
//! not block on a `gh` round-trip on every render.
//!
//! Schema is locked by migration 0008:
//!
//! ```sql
//! CREATE TABLE pull_requests (
//!     id TEXT PRIMARY KEY,
//!     workarea_id TEXT NOT NULL REFERENCES workareas(id) ON DELETE CASCADE,
//!     repository_id TEXT NOT NULL REFERENCES repositories(id),
//!     provider TEXT NOT NULL,
//!     pr_number INTEGER NOT NULL,
//!     base_ref TEXT NOT NULL,
//!     head_ref TEXT NOT NULL,
//!     state TEXT NOT NULL,
//!     title TEXT NOT NULL,
//!     body TEXT NOT NULL DEFAULT '',
//!     url TEXT NOT NULL DEFAULT '',
//!     head_sha TEXT NOT NULL DEFAULT '',
//!     created_at INTEGER NOT NULL,
//!     updated_at INTEGER NOT NULL,
//!     UNIQUE(workarea_id, repository_id)
//! );
//! ```
//!
//! Public types are declared in [`crate::api`] so the interface
//! generator picks them up.

use concerto_error::{Error, Result};
use sqlx::{Row, SqliteConnection, SqlitePool};

use crate::api::{NewPullRequest, PullRequest, PullRequestId};

/// Insert OR update the row keyed by `(workarea_id, repository_id)`.
///
/// `id` is generated by the caller (UUIDv7) and used only on the
/// first insert — subsequent upserts keep the existing primary key so
/// callers holding the original id stay valid. `created_at` is also
/// preserved across upserts; `updated_at` always advances to the
/// caller-supplied value.
pub async fn upsert(conn: &mut SqliteConnection, row: NewPullRequest) -> Result<PullRequestId> {
    sqlx::query(
        "INSERT INTO pull_requests (
            id, workarea_id, repository_id, provider, pr_number,
            base_ref, head_ref, state, title, body, url, head_sha,
            created_at, updated_at
         ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
         ON CONFLICT(workarea_id, repository_id) DO UPDATE SET
            provider   = excluded.provider,
            pr_number  = excluded.pr_number,
            base_ref   = excluded.base_ref,
            head_ref   = excluded.head_ref,
            state      = excluded.state,
            title      = excluded.title,
            body       = excluded.body,
            url        = excluded.url,
            head_sha   = excluded.head_sha,
            updated_at = excluded.updated_at",
    )
    .bind(&row.id.0)
    .bind(&row.workarea_id.0)
    .bind(&row.repository_id.0)
    .bind(&row.provider)
    .bind(row.pr_number)
    .bind(&row.base_ref)
    .bind(&row.head_ref)
    .bind(&row.state)
    .bind(&row.title)
    .bind(&row.body)
    .bind(&row.url)
    .bind(&row.head_sha)
    .bind(row.created_at)
    .bind(row.updated_at)
    .execute(&mut *conn)
    .await
    .map_err(|e| Error::Sqlx(Box::new(e)))?;

    // Resolve the canonical id (the existing one if this was an UPDATE,
    // the new one otherwise). One SELECT keeps the upsert call site
    // honest about which id the caller now owns.
    let resolved: String = sqlx::query_scalar(
        "SELECT id FROM pull_requests WHERE workarea_id = ? AND repository_id = ?",
    )
    .bind(&row.workarea_id.0)
    .bind(&row.repository_id.0)
    .fetch_one(conn)
    .await
    .map_err(|e| Error::Sqlx(Box::new(e)))?;
    Ok(PullRequestId(resolved))
}

/// Fetch one PR by primary key (read-only).
pub async fn get(pool: &SqlitePool, id: &PullRequestId) -> Result<Option<PullRequest>> {
    let row = sqlx::query(
        "SELECT id, workarea_id, repository_id, provider, pr_number,
                base_ref, head_ref, state, title, body, url, head_sha,
                created_at, updated_at
         FROM pull_requests WHERE id = ?",
    )
    .bind(&id.0)
    .fetch_optional(pool)
    .await
    .map_err(|e| Error::Sqlx(Box::new(e)))?;
    Ok(row.map(row_to_pull_request))
}

/// List every PR for `workarea_id` (read-only). Ordered by `pr_number`
/// for deterministic UI rendering.
pub async fn list_by_workarea(
    pool: &SqlitePool,
    workarea_id: &crate::api::WorkareaId,
) -> Result<Vec<PullRequest>> {
    let rows = sqlx::query(
        "SELECT id, workarea_id, repository_id, provider, pr_number,
                base_ref, head_ref, state, title, body, url, head_sha,
                created_at, updated_at
         FROM pull_requests WHERE workarea_id = ? ORDER BY pr_number",
    )
    .bind(&workarea_id.0)
    .fetch_all(pool)
    .await
    .map_err(|e| Error::Sqlx(Box::new(e)))?;
    Ok(rows.into_iter().map(row_to_pull_request).collect())
}

fn row_to_pull_request(row: sqlx::sqlite::SqliteRow) -> PullRequest {
    use crate::api::{RepositoryId, WorkareaId};
    PullRequest {
        id: PullRequestId(row.get::<String, _>("id")),
        workarea_id: WorkareaId(row.get::<String, _>("workarea_id")),
        repository_id: RepositoryId(row.get::<String, _>("repository_id")),
        provider: row.get::<String, _>("provider"),
        pr_number: row.get::<i64, _>("pr_number"),
        base_ref: row.get::<String, _>("base_ref"),
        head_ref: row.get::<String, _>("head_ref"),
        state: row.get::<String, _>("state"),
        title: row.get::<String, _>("title"),
        body: row.get::<String, _>("body"),
        url: row.get::<String, _>("url"),
        head_sha: row.get::<String, _>("head_sha"),
        created_at: row.get::<i64, _>("created_at"),
        updated_at: row.get::<i64, _>("updated_at"),
    }
}
