-- 0001_initial_schema.sql — Concerto V0.1 core entity schema.
--
-- Rewritten 2026-06-08 as part of the Project→Workspace collapse (D5).
-- The `projects` table has been removed; repositories and workspaces are
-- now top-level (global registry). This is a one-time approved exception
-- to the frozen-migrations discipline — there is no deployed database and
-- no backward-compatibility requirement.
--
-- Source of truth: design/09_Persistence.md §4.1, §4.2, §4.4. Column
-- names match the design doc one-for-one. Tables for schedules,
-- skills_index, suggestion_learn, todos, and pull_requests are
-- intentionally deferred — they arrive in their owning Phase 3 tasks
-- (38, 39, 40, 45) so the schema for unbuilt subsystems doesn't lock
-- in before those subsystems are designed in code.
--
-- Conventions used throughout:
--   * Primary keys are TEXT (UUIDv7 generated by the application).
--   * Timestamps are INTEGER (unix epoch milliseconds), never TEXT.
--   * JSON columns are TEXT (sqlx handles them cleanly; we don't rely
--     on SQLite's JSON1 type alias).
--   * `status` is TEXT NOT NULL CHECK(...) matching the value list
--     declared in the corresponding proto's field comment (see
--     crates/proto/proto/concerto/v1/*.proto). The proto field stays
--     `string` for forward compat; the DB CHECK is the enforcement.
--   * `permission_mode` is nullable on workspaces and workareas to
--     express "inherit from workspace" (design/03 §3.2 + proto `optional`
--     PermissionMode). NULL ≠ PERMISSION_MODE_UNSPECIFIED.
--   * Foreign keys use ON DELETE CASCADE where the child has no
--     meaning without its parent (design/09 §4.1 implies this for the
--     workspace → workarea → session chain). FKs are enforced at runtime
--     because crates/persist sets `foreign_keys = ON` on every connection
--     (Task 08).
--
-- Transaction wrapping: `sqlx::migrate!` runs each .sql file inside an
-- implicit `BEGIN; ... COMMIT;` (design/09 §6.2's "single transaction
-- per file" guarantee). Adding our own BEGIN here would error with
-- "cannot start a transaction within a transaction", so we don't.

-- ---------------------------------------------------------------------------
-- Repositories: global registry. Clone lives at ~/concerto/repos/<id>/.git
-- and is shared across all workareas (one .git, many worktrees). Referenced
-- by workspaces via workspace_repos. design/09 §4.1.
-- ---------------------------------------------------------------------------
CREATE TABLE repositories (
    id                  TEXT PRIMARY KEY,
    name                TEXT NOT NULL,                 -- short name used in folder paths
    url                 TEXT NOT NULL,
    local_path          TEXT NOT NULL,                 -- ~/concerto/repos/<id>/
    clone_strategy      TEXT NOT NULL,                 -- full | blobless | treeless
    default_branch      TEXT NOT NULL,
    cone_defaults_json  TEXT NOT NULL DEFAULT '[]',
    fs_monitor_pid      INTEGER,
    last_fetch_at       INTEGER,
    UNIQUE(url),
    UNIQUE(name)
);

-- ---------------------------------------------------------------------------
-- Workspaces: a logical workstream. No own worktree; 1..N repos via
-- workspace_repos. Top-level entity after the Project→Workspace collapse.
-- design/09 §4.1.
--
-- `permission_mode` and `bypass_destructive_guard` are nullable: NULL means
-- "inherit from workspace defaults" per design/03 §3.2.
-- ---------------------------------------------------------------------------
CREATE TABLE workspaces (
    id                          TEXT PRIMARY KEY,
    name                        TEXT NOT NULL,
    slug                        TEXT NOT NULL,
    icon                        TEXT,
    description                 TEXT,
    permission_mode             TEXT CHECK (permission_mode IS NULL OR permission_mode IN ('strict','normal','auto','yolo')),
    bypass_destructive_guard    INTEGER CHECK (bypass_destructive_guard IS NULL OR bypass_destructive_guard IN (0,1)),
    settings_json               TEXT NOT NULL DEFAULT '{}',
    created_at                  INTEGER NOT NULL,
    archived_at                 INTEGER,
    UNIQUE(slug)
);

-- ---------------------------------------------------------------------------
-- Workspace ↔ repository join. `position` is the per-workspace 0-based
-- ordinal (folded in from migration 0009 by the Project→Workspace collapse).
-- `sparse_cones_json` is the per-(workspace, repo) sparse cone set.
-- design/09 §4.1.
-- ---------------------------------------------------------------------------
CREATE TABLE workspace_repos (
    workspace_id      TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
    repository_id     TEXT NOT NULL REFERENCES repositories(id),
    position          INTEGER NOT NULL DEFAULT 0,
    sparse_cones_json TEXT NOT NULL DEFAULT '[]',
    PRIMARY KEY (workspace_id, repository_id)
);

-- Ordered-read index for `list_repos` (and Task 309's first-by-position
-- reference-repo lookup). Originally from migration 0009; folded here by
-- the Project→Workspace collapse (2026-06-08).
CREATE INDEX idx_workspace_repos_position ON workspace_repos(workspace_id, position);

-- ---------------------------------------------------------------------------
-- Workareas: a specific attempt at a workspace's task. Worktrees on disk.
-- One workspace → 1..N workareas. design/09 §4.1.
--
-- `status` values match the value list in
-- crates/proto/proto/concerto/v1/workareas.proto. `permission_mode` and
-- `bypass_destructive_guard` are nullable for the same inherit-from-workspace
-- reason as workspaces.
-- ---------------------------------------------------------------------------
CREATE TABLE workareas (
    id                          TEXT PRIMARY KEY,
    workspace_id                TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
    composer_name               TEXT NOT NULL,
    branch_name                 TEXT NOT NULL,
    worktree_root               TEXT NOT NULL,
    status                      TEXT NOT NULL CHECK (status IN (
        'created','active','running','awaiting','paused','archived','crashed'
    )),
    permission_mode             TEXT CHECK (permission_mode IS NULL OR permission_mode IN ('strict','normal','auto','yolo')),
    bypass_destructive_guard    INTEGER CHECK (bypass_destructive_guard IS NULL OR bypass_destructive_guard IN (0,1)),
    created_at                  INTEGER NOT NULL,
    archived_at                 INTEGER,
    last_activity_at            INTEGER,
    UNIQUE(workspace_id, composer_name)
);

CREATE INDEX idx_workareas_status ON workareas(status);
CREATE INDEX idx_workareas_workspace ON workareas(workspace_id);

-- ---------------------------------------------------------------------------
-- Per-(workarea, repo) state: each repo's worktree path, sparse cones, and
-- optional per-repo branch override. design/09 §4.1.
-- ---------------------------------------------------------------------------
CREATE TABLE workarea_repos (
    workarea_id         TEXT NOT NULL REFERENCES workareas(id) ON DELETE CASCADE,
    repository_id       TEXT NOT NULL REFERENCES repositories(id),
    worktree_path       TEXT NOT NULL,
    branch_override     TEXT,
    sparse_cones_json   TEXT NOT NULL DEFAULT '[]',
    PRIMARY KEY (workarea_id, repository_id)
);

-- ---------------------------------------------------------------------------
-- Chats: each session has exactly one chat. The maestro chat is the
-- singleton with kind='maestro' and session_id IS NULL.
-- design/09 §4.1.
--
-- Note: the `REFERENCES sessions(id)` here is a forward reference within
-- this same transaction — `sessions` is created below. SQLite resolves
-- foreign keys at execution time, not at table-creation time, so this is
-- safe inside a BEGIN/COMMIT block.
-- ---------------------------------------------------------------------------
CREATE TABLE chats (
    id              TEXT PRIMARY KEY,
    session_id      TEXT REFERENCES sessions(id) ON DELETE CASCADE,
    kind            TEXT NOT NULL CHECK (kind IN ('session','maestro')),
    created_at      INTEGER NOT NULL,
    CHECK ( (session_id IS NOT NULL) OR kind = 'maestro' )
);

CREATE TABLE chat_messages (
    id              TEXT PRIMARY KEY,
    chat_id         TEXT NOT NULL REFERENCES chats(id) ON DELETE CASCADE,
    role            TEXT NOT NULL CHECK (role IN ('user','assistant','system','tool')),
    content_json    TEXT NOT NULL,
    created_at      INTEGER NOT NULL,
    parent_id       TEXT REFERENCES chat_messages(id),
    superseded_by   TEXT REFERENCES chat_messages(id)
);

CREATE INDEX idx_chat_messages_chat ON chat_messages(chat_id, created_at);

-- ---------------------------------------------------------------------------
-- Sessions: a specific agent run on a workarea. design/09 §4.2.
--
-- `agent_kind` includes 'gemini' for forward compat even though V0.1 wires
-- only claude + codex (per tasks/README.md §2 and Task 08 handoff note).
-- `status` matches crates/proto/proto/concerto/v1/sessions.proto.
-- ---------------------------------------------------------------------------
CREATE TABLE sessions (
    id                          TEXT PRIMARY KEY,
    workarea_id                 TEXT NOT NULL REFERENCES workareas(id) ON DELETE CASCADE,
    chat_id                     TEXT NOT NULL REFERENCES chats(id),
    agent_kind                  TEXT NOT NULL CHECK (agent_kind IN ('claude','codex','gemini','maestro')),
    agent_version               TEXT,
    model                       TEXT,
    mode                        TEXT,
    host_pid                    INTEGER,
    host_socket                 TEXT,
    pty_cookie                  BLOB,
    external_session_id         TEXT,
    permission_mode             TEXT NOT NULL DEFAULT 'normal' CHECK (permission_mode IN ('strict','normal','auto','yolo')),
    bypass_destructive_guard    INTEGER NOT NULL DEFAULT 0 CHECK (bypass_destructive_guard IN (0,1)),
    started_at                  INTEGER NOT NULL,
    ended_at                    INTEGER,
    last_heartbeat              INTEGER,
    status                      TEXT NOT NULL CHECK (status IN (
        'starting','running','awaiting','finished','crashed'
    ))
);

CREATE INDEX idx_sessions_workarea ON sessions(workarea_id);
CREATE INDEX idx_sessions_status ON sessions(status) WHERE status IN ('starting','running','awaiting');
CREATE INDEX idx_sessions_yolo ON sessions(permission_mode) WHERE permission_mode IN ('auto','yolo');

-- ---------------------------------------------------------------------------
-- Checkpoints: per-(workarea, repo) snapshot of a turn. A turn touching
-- multiple repos produces multiple rows. design/09 §4.2.
-- ---------------------------------------------------------------------------
CREATE TABLE checkpoints (
    id              TEXT PRIMARY KEY,
    workarea_id     TEXT NOT NULL REFERENCES workareas(id) ON DELETE CASCADE,
    repository_id   TEXT NOT NULL REFERENCES repositories(id),
    chat_message_id TEXT NOT NULL REFERENCES chat_messages(id),
    git_ref         TEXT NOT NULL,
    created_at      INTEGER NOT NULL,
    diff_stats_json TEXT
);

CREATE INDEX idx_checkpoints_workarea ON checkpoints(workarea_id);

-- ---------------------------------------------------------------------------
-- Tool approvals: each tool call the agent requests, with its disposition.
-- design/09 §4.2.
-- ---------------------------------------------------------------------------
CREATE TABLE tool_approvals (
    id                      TEXT PRIMARY KEY,
    session_id              TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    tool_name               TEXT NOT NULL,
    payload_json            TEXT NOT NULL,
    requested_at            INTEGER NOT NULL,
    decided_at              INTEGER,
    decided_by_device_id    TEXT REFERENCES devices(id),
    decision                TEXT CHECK (decision IS NULL OR decision IN (
        'approve','approve_once','deny','auto_strict','auto_normal','auto_auto','auto_yolo'
    ))
);

-- ---------------------------------------------------------------------------
-- Devices: paired clients (desktop + mobile). design/09 §4.4.
-- Identity is the Ed25519 public-key fingerprint.
-- ---------------------------------------------------------------------------
CREATE TABLE devices (
    id              TEXT PRIMARY KEY,                  -- public key fingerprint
    name            TEXT NOT NULL,
    public_key      BLOB NOT NULL,                     -- Ed25519
    paired_at       INTEGER NOT NULL,
    last_seen_at    INTEGER,
    revoked_at      INTEGER,
    push_token      TEXT,
    push_platform   TEXT CHECK (push_platform IS NULL OR push_platform IN ('apns','fcm'))
);

CREATE INDEX idx_devices_active ON devices(revoked_at) WHERE revoked_at IS NULL;
