#!/usr/bin/env bash
# shellcheck disable=SC2016
# (SC2016: many printf format strings embed literal markdown backticks; they
# are not meant to be shell-expanded.)
#
# Concerto interface-summary generator.
#
# Encodes decision D4 from tasks/README.md §3: schema files (.proto,
# migrations/*.sql, pub Rust modules at crates/<crate>/src/api.rs) are
# canonical. This script produces deterministic markdown summaries of those
# canonical artifacts under docs/interfaces/. Subsequent tasks reference
# those summaries as the "what's public so far" cheat sheet, and CI fails
# any commit that changes the canonical artifacts without regenerating.
#
# Determinism contract: same inputs always produce byte-identical outputs.
# No timestamps, no random IDs, file order sorted by path.
#
# Linux/macOS only (bash 3.2-compatible).

set -euo pipefail

HEADER='<!-- AUTO-GENERATED by scripts/regen-interfaces.sh — do not edit by hand. -->'

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT_DIR="$ROOT/docs/interfaces"
mkdir -p "$OUT_DIR"

# ----------------------------------------------------------------------------
# Helpers
# ----------------------------------------------------------------------------

# emit_brace_blocks <decl-regex> <fence-lang> <file>
#   Scan <file> for top-level declarations matching <decl-regex>, capture the
#   brace-balanced region starting with each match, and emit the region inside
#   a ```<fence-lang> code fence. <decl-regex> is an extended regex; the first
#   captured token after the keyword is treated as the declaration name.
emit_brace_blocks() {
    local decl_regex=$1
    local fence_lang=$2
    local file=$3
    awk -v decl_regex="$decl_regex" -v fence_lang="$fence_lang" '
        function n_open(s,    n, arr) { n = split(s, arr, /\{/); return n - 1 }
        function n_close(s,   n, arr) { n = split(s, arr, /\}/); return n - 1 }
        BEGIN { depth = 0; first = 1 }
        depth == 0 && $0 ~ decl_regex {
            # Identify keyword and name
            n = split($0, toks, /[[:space:]]+/)
            keyword = ""
            name = ""
            for (i = 1; i <= n; i++) {
                if (toks[i] ~ /^(message|service|enum|pub)$/) {
                    if (toks[i] == "pub") {
                        keyword = toks[i+1]
                        name = toks[i+2]
                    } else {
                        keyword = toks[i]
                        name = toks[i+1]
                    }
                    break
                }
            }
            # Strip trailing punctuation from name (e.g. "Foo<T>" keeps generics,
            # but "Foo;" -> "Foo" and "Foo(" -> "Foo")
            sub(/[<({;,].*$/, "", name)
            if (!first) print ""
            first = 0
            print "### " keyword " `" name "`"
            print ""
            print "```" fence_lang
            print $0
            depth += n_open($0) - n_close($0)
            # Terminate immediately when the opening line is itself complete:
            # either braces balance on the same line (e.g. `pub trait Foo {}`)
            # or there are no braces and the line ends in ; (tuple struct,
            # unit struct, type alias).
            if (depth <= 0) {
                print "```"
                depth = 0
            }
            next
        }
        depth > 0 {
            print $0
            depth += n_open($0) - n_close($0)
            if (depth <= 0) {
                print "```"
                depth = 0
            }
            next
        }
    ' "$file"
}

# ----------------------------------------------------------------------------
# Proto
# ----------------------------------------------------------------------------

gen_proto() {
    local out="$OUT_DIR/proto.md"
    local tmp
    tmp=$(mktemp)
    {
        printf '%s\n\n' "$HEADER"
        printf '# Proto\n\n'
        local proto_root="$ROOT/crates/proto/proto"
        if [ -d "$proto_root" ] && find "$proto_root" -type f -name '*.proto' -print -quit | grep -q .; then
            local f rel pkg
            while IFS= read -r -d '' f; do
                rel="${f#"$ROOT"/}"
                printf '## `%s`\n\n' "$rel"
                pkg=$(awk '
                    /^[[:space:]]*package[[:space:]]+/ {
                        line = $0
                        sub(/^[[:space:]]*package[[:space:]]+/, "", line)
                        sub(/;.*$/, "", line)
                        gsub(/[[:space:]]+/, "", line)
                        print line
                        exit
                    }' "$f")
                if [ -n "$pkg" ]; then
                    printf -- '- package: `%s`\n\n' "$pkg"
                fi
                emit_brace_blocks '^[[:space:]]*(message|service|enum)[[:space:]]+[A-Za-z_]' proto "$f"
                printf '\n'
            done < <(find "$proto_root" -type f -name '*.proto' -print0 | sort -z)
        else
            printf '_No `.proto` files yet._\n'
        fi
    } > "$tmp"
    mv "$tmp" "$out"
}

# ----------------------------------------------------------------------------
# SQL migrations
# ----------------------------------------------------------------------------

gen_schema() {
    local out="$OUT_DIR/schema.md"
    local tmp
    tmp=$(mktemp)
    {
        printf '%s\n\n' "$HEADER"
        printf '# Schema (SQLite migrations)\n\n'
        local mig_dir="$ROOT/crates/persist/migrations"
        if [ -d "$mig_dir" ] && find "$mig_dir" -type f -name '*.sql' -print -quit | grep -q .; then
            local f rel
            while IFS= read -r -d '' f; do
                rel="${f#"$ROOT"/}"
                printf '## `%s`\n\n' "$rel"
                # Capture CREATE TABLE / CREATE INDEX statements verbatim until
                # the terminating semicolon. Other statements are skipped.
                awk '
                    function n_lparen(s,  n, arr) { n = split(s, arr, /\(/); return n - 1 }
                    function n_rparen(s,  n, arr) { n = split(s, arr, /\)/); return n - 1 }
                    BEGIN { collecting = 0; first = 1 }
                    !collecting && /^[[:space:]]*CREATE[[:space:]]+(TABLE|INDEX)/ {
                        if (!first) print ""
                        first = 0
                        print "```sql"
                        print $0
                        collecting = 1
                        if ($0 ~ /;[[:space:]]*(--.*)?$/ && n_lparen($0) == n_rparen($0)) {
                            print "```"
                            collecting = 0
                        }
                        next
                    }
                    collecting {
                        print $0
                        if ($0 ~ /;[[:space:]]*(--.*)?$/) {
                            print "```"
                            collecting = 0
                        }
                        next
                    }
                ' "$f"
                printf '\n'
            done < <(find "$mig_dir" -type f -name '*.sql' -print0 | sort -z)
        else
            printf '_No migrations yet._\n'
        fi
    } > "$tmp"
    mv "$tmp" "$out"
}

# ----------------------------------------------------------------------------
# Rust API
# ----------------------------------------------------------------------------

gen_rust_api() {
    local out="$OUT_DIR/rust-api.md"
    local tmp
    tmp=$(mktemp)
    {
        printf '%s\n\n' "$HEADER"
        printf '# Public Rust API\n\n'
        # Find every crates/<crate>/src/api.rs (per the locked convention from
        # this task). Sort by path so output is deterministic.
        local api_files
        api_files=$(find "$ROOT/crates" -mindepth 3 -maxdepth 3 -type f -path '*/src/api.rs' 2>/dev/null | sort || true)
        if [ -n "$api_files" ]; then
            local f rel
            while IFS= read -r f; do
                [ -z "$f" ] && continue
                rel="${f#"$ROOT"/}"
                printf '## `%s`\n\n' "$rel"
                emit_brace_blocks '^[[:space:]]*pub[[:space:]]+(trait|struct|enum)[[:space:]]+[A-Za-z_]' rust "$f"
                printf '\n'
            done <<< "$api_files"
        else
            printf '_No `crates/*/src/api.rs` files yet._\n'
        fi
    } > "$tmp"
    mv "$tmp" "$out"
}

# ----------------------------------------------------------------------------
# Run
# ----------------------------------------------------------------------------

gen_proto
gen_schema
gen_rust_api

echo "Regenerated: docs/interfaces/{proto,schema,rust-api}.md"
