//! Noise XX pairing handshake bootstrapped by the one-shot pairing token
//! (`design/12 §3.3`, §7.1, Task 207).
//!
//! The device-pairing ceremony runs a **Noise XX** (mutual-unauthenticated)
//! handshake whose pre-shared key is the 32-byte `pairing_token` both ends know
//! from the QR payload. Using the token as the Noise PSK is what gives the
//! otherwise-anonymous XX handshake its authentication: an attacker who never
//! saw the QR cannot complete the handshake, because they lack the PSK
//! (`design/12 §3.3`: "both ends authenticate via the `pairing_token`").
//!
//! # FROZEN wire contract — the Noise protocol string
//!
//! ```text
//! Noise_XXpsk3_25519_AESGCM_SHA256
//! ```
//!
//! - **`XX`** — the mutual-unauthenticated pattern: neither side knows the
//!   other's static key in advance (first contact), and both transmit their
//!   static key inside the encrypted handshake. (Post-pairing IK reuse is
//!   Task 208's separate session layer — do not conflate.)
//! - **`psk3`** — the PSK is mixed at message index 3 (i.e. after the third XX
//!   handshake message, `-> s, se`). `psk3` is the placement `snow` supports
//!   cleanly for XX and the latest point at which the PSK can bind the channel,
//!   so a handshake that reaches the transport phase has provably mixed the
//!   token on **both** ends — exactly the "both ends authenticate via the
//!   token" requirement. A wrong PSK makes the final `read_message` fail with a
//!   decrypt error, which the coordinator maps to a dropped pairing (`design/12
//!   §8`: "Noise handshake fails → drop connection").
//! - **`25519_AESGCM_SHA256`** — X25519 DH, AES-256-GCM AEAD, SHA-256 hash.
//!
//! Both the initiator (the pairing device) and the responder (the Core) MUST
//! use this exact string; it is the frozen wire contract for the pairing
//! channel. Changing it would break interoperability with any already-shipped
//! client.
//!
//! # Transport-agnostic
//!
//! This module is a thin `snow` wrapper that exchanges the three XX handshake
//! messages over a **caller-supplied byte duplex** and yields a completed
//! [`NoiseTransport`] on which the application payload (the
//! `PairingRequest`) is sent encrypted. It knows nothing about Iroh, TCP, or
//! `tokio::io::duplex` — the caller (the pairing coordinator, or the Tier-2
//! loopback test) drives the byte exchange. The three messages flow:
//!
//! ```text
//! initiator -> responder :  e
//! responder -> initiator :  e, ee, s, es
//! initiator -> responder :  s, se   (+ psk mixed at this index)
//! ```
//!
//! After the third message both ends call [`NoiseHandshake::into_transport`]
//! and then [`NoiseTransport::write_message`] / [`NoiseTransport::read_message`]
//! to exchange encrypted application frames.

use snow::{Builder, HandshakeState, TransportState};

use crate::error::IdentityError;

/// The FROZEN Noise protocol string for the pairing channel. See the module
/// doc for the placement rationale.
pub const PAIRING_NOISE_PARAMS: &str = "Noise_XXpsk3_25519_AESGCM_SHA256";

/// The PSK index at which the pairing token is mixed (`psk3`). Frozen
/// alongside [`PAIRING_NOISE_PARAMS`]; both ends pass the token at this index.
const PSK_INDEX: u8 = 3;

/// A Noise message buffer ceiling. Noise messages are ≤ 65535 bytes; the
/// pairing handshake + the single `PairingRequest` payload are far smaller, but
/// we size the scratch buffer at the protocol max so a write never truncates.
const MAX_NOISE_MSG: usize = 65535;

/// One side of an in-progress Noise XX pairing handshake.
///
/// Build an [`initiator`](NoiseHandshake::initiator) (the pairing device) or a
/// [`responder`](NoiseHandshake::responder) (the Core), then drive the three XX
/// messages with [`write_message`](Self::write_message) /
/// [`read_message`](Self::read_message) in the order the pattern dictates.
/// When [`is_handshake_finished`](Self::is_handshake_finished) returns `true`,
/// call [`into_transport`](Self::into_transport).
pub struct NoiseHandshake {
    state: HandshakeState,
}

impl NoiseHandshake {
    /// Build the **initiator** side (the pairing device).
    ///
    /// `pairing_token` is the raw 32-byte token from the QR payload, used as
    /// the Noise PSK. A fresh ephemeral + static keypair is generated by `snow`
    /// for the handshake; the device's *pairing* Ed25519 identity is a separate
    /// key carried inside the encrypted `PairingRequest`, not the Noise static
    /// key (the Noise static key authenticates only the channel).
    pub fn initiator(pairing_token: &[u8; 32]) -> Result<Self, IdentityError> {
        Self::build(pairing_token, true)
    }

    /// Build the **responder** side (the Core).
    ///
    /// `pairing_token` is the raw 32-byte token the Core minted and embedded in
    /// the QR; it must match the initiator's PSK or the handshake fails.
    pub fn responder(pairing_token: &[u8; 32]) -> Result<Self, IdentityError> {
        Self::build(pairing_token, false)
    }

    fn build(pairing_token: &[u8; 32], initiator: bool) -> Result<Self, IdentityError> {
        let params = PAIRING_NOISE_PARAMS
            .parse()
            .map_err(|e| IdentityError::Noise(format!("invalid noise params: {e}")))?;
        let mut builder = Builder::new(params).psk(PSK_INDEX, pairing_token);
        // XX transmits each side's static key inside the handshake, so both
        // ends need a local static keypair. Generate a fresh one per handshake.
        let keypair = builder
            .generate_keypair()
            .map_err(|e| IdentityError::Noise(format!("generate keypair: {e}")))?;
        builder = builder.local_private_key(&keypair.private);
        let state = if initiator {
            builder.build_initiator()
        } else {
            builder.build_responder()
        }
        .map_err(|e| IdentityError::Noise(format!("build handshake: {e}")))?;
        Ok(Self { state })
    }

    /// Write the next handshake message, returning the bytes to send to the
    /// peer. `payload` is optional in-handshake application data (the pairing
    /// flow sends none during the handshake — the `PairingRequest` rides the
    /// transport phase — so pass `&[]`).
    pub fn write_message(&mut self, payload: &[u8]) -> Result<Vec<u8>, IdentityError> {
        let mut buf = vec![0u8; MAX_NOISE_MSG];
        let n = self
            .state
            .write_message(payload, &mut buf)
            .map_err(|e| IdentityError::Noise(format!("write handshake message: {e}")))?;
        buf.truncate(n);
        Ok(buf)
    }

    /// Read a handshake message received from the peer, returning any
    /// in-handshake application payload (empty for the pairing flow). A decrypt
    /// failure here — including a **wrong PSK** (mismatched pairing token) —
    /// surfaces as [`IdentityError::Noise`]; the coordinator drops the pairing.
    pub fn read_message(&mut self, message: &[u8]) -> Result<Vec<u8>, IdentityError> {
        let mut buf = vec![0u8; MAX_NOISE_MSG];
        let n = self
            .state
            .read_message(message, &mut buf)
            .map_err(|e| IdentityError::Noise(format!("read handshake message: {e}")))?;
        buf.truncate(n);
        Ok(buf)
    }

    /// Whether the handshake has completed all its messages on this side.
    pub fn is_handshake_finished(&self) -> bool {
        self.state.is_handshake_finished()
    }

    /// Consume the finished handshake and derive the post-handshake transport
    /// (AES-256-GCM in both directions). Errors if the handshake is not yet
    /// finished.
    pub fn into_transport(self) -> Result<NoiseTransport, IdentityError> {
        let transport = self
            .state
            .into_transport_mode()
            .map_err(|e| IdentityError::Noise(format!("enter transport mode: {e}")))?;
        Ok(NoiseTransport { state: transport })
    }
}

/// A completed Noise XX session: the AES-256-GCM transport on which the pairing
/// device sends its encrypted `PairingRequest` and the Core replies.
pub struct NoiseTransport {
    state: TransportState,
}

impl NoiseTransport {
    /// Encrypt `payload` into a Noise transport message to send to the peer.
    pub fn write_message(&mut self, payload: &[u8]) -> Result<Vec<u8>, IdentityError> {
        let mut buf = vec![0u8; payload.len() + MAX_NOISE_MSG.min(1024) + 16];
        // The ciphertext is `payload.len() + 16` (AEAD tag); size generously.
        if buf.len() < payload.len() + 16 {
            buf.resize(payload.len() + 16, 0);
        }
        let n = self
            .state
            .write_message(payload, &mut buf)
            .map_err(|e| IdentityError::Noise(format!("encrypt transport message: {e}")))?;
        buf.truncate(n);
        Ok(buf)
    }

    /// Decrypt a Noise transport message received from the peer.
    pub fn read_message(&mut self, message: &[u8]) -> Result<Vec<u8>, IdentityError> {
        let mut buf = vec![0u8; message.len() + 16];
        let n = self
            .state
            .read_message(message, &mut buf)
            .map_err(|e| IdentityError::Noise(format!("decrypt transport message: {e}")))?;
        buf.truncate(n);
        Ok(buf)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Drive a full XX handshake in-process between two sides over a Vec-based
    /// "channel" and return both completed transports.
    fn complete_handshake(
        token_init: &[u8; 32],
        token_resp: &[u8; 32],
    ) -> Result<(NoiseTransport, NoiseTransport), IdentityError> {
        let mut ini = NoiseHandshake::initiator(token_init)?;
        let mut res = NoiseHandshake::responder(token_resp)?;

        // -> e
        let m1 = ini.write_message(&[])?;
        res.read_message(&m1)?;
        // <- e, ee, s, es
        let m2 = res.write_message(&[])?;
        ini.read_message(&m2)?;
        // -> s, se (psk mixed here)
        let m3 = ini.write_message(&[])?;
        res.read_message(&m3)?;

        assert!(ini.is_handshake_finished());
        assert!(res.is_handshake_finished());
        Ok((ini.into_transport()?, res.into_transport()?))
    }

    #[test]
    fn matching_token_completes_and_transports_payload() {
        let token = [7u8; 32];
        let (mut ini_t, mut res_t) =
            complete_handshake(&token, &token).expect("handshake with matching token");

        // Initiator sends an encrypted payload; responder decrypts it.
        let plaintext = b"PairingRequest payload bytes";
        let ct = ini_t.write_message(plaintext).expect("encrypt");
        assert_ne!(&ct[..], &plaintext[..], "payload must be encrypted on wire");
        let pt = res_t.read_message(&ct).expect("decrypt");
        assert_eq!(&pt[..], &plaintext[..]);

        // And the reverse direction (Core's reply).
        let reply = b"SignedDeviceCert bytes";
        let ct2 = res_t.write_message(reply).expect("encrypt reply");
        let pt2 = ini_t.read_message(&ct2).expect("decrypt reply");
        assert_eq!(&pt2[..], &reply[..]);
    }

    #[test]
    fn mismatched_token_fails_handshake() {
        // Different PSKs: the psk3 mix diverges, so the responder's read of the
        // final message fails to authenticate.
        let res = complete_handshake(&[1u8; 32], &[2u8; 32]);
        assert!(
            res.is_err(),
            "a wrong pairing token (PSK) must fail the handshake"
        );
    }

    #[test]
    fn protocol_string_is_frozen() {
        // Guards the frozen wire contract — a change here is a breaking change
        // to every shipped client.
        assert_eq!(PAIRING_NOISE_PARAMS, "Noise_XXpsk3_25519_AESGCM_SHA256");
    }
}
